### ISSUE TITLE
Release note tags

### ISSUE THREAD

**Issue by OzBob** [DrJohnT/PublishDacPac#4]
Hi,

I'm reading through the source to audit it for my own peace of mind, and noticed, that:

["PublishDacPac.psd1#L93" ](https://github.com/DrJohnT/PublishDacPac/blob/master/PublishDacPac/PublishDacPac.psd1#L93)

links to ```https://github.com/DrJohnT/PublishDacPac/releases/tag/1.1.0``` but your [GitHub releases](https://github.com/DrJohnT/PublishDacPac/releases/) only has 1.0.2, and the [PowershellGallery](https://www.powershellgallery.com/packages/PublishDacPac/1.1.1) has 1.1.1.

Am i seeing the latest source in GitHub?

**Comment by DrJohnT** [comment]
GitHub has the only copy of the source code.  I never got used to using the GitHub releases, so I probably forgot.
